[project]
name = "goit-algo-fp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "pulp>=3.3.0",
]

[dependency-groups]
dev = [
    "types-networkx>=3.6.1.20251220",
]
